runtime: python27
api_version: 1
threadsafe: yes

#[START_EXCLUDE]
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?setuptools/script \(dev\).tmpl$
#[END_EXCLUDE]

handlers:
# The endpoints handler must be mapped to /_ah/api.
- url: /_ah/api/.*
  script: main.api

libraries:
#- name: endpoints
#  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11
- name: webapp2
  version: latest
